#!/usr/bin/env bash
# Build the standalone WarpX executable. Extra arguments go to the configure step.
. "$(dirname "${BASH_SOURCE[0]}")/warpx-env.sh"

root=$(warpx_root)
warpx_require_submodule "$root"
warpx_export_toolchain

src="$root/vendor/warpx"

cmake -S "$src" -B "$src/build" -G Ninja \
    -DWarpX_MPI=OFF -DWarpX_COMPUTE=OMP -DWarpX_DIMS=3 -DWarpX_FFT=ON "$@"
cmake --build "$src/build" -j "$(warpx_ncpu)"
